# Generated by Django 2.1.7 on 2019-03-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_operation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operation',
            new_name='Movement',
        ),
    ]
